In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Load Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Standardize the data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [2]:
class GenSVM:
    def __init__(self, lambda_param=1.0, p=2, kappa=0):
        self.lambda_param = lambda_param
        self.p = p
        self.kappa = kappa

    def fit(self, X, y):
        n, m = X.shape
        K = len(np.unique(y))
        self.W = np.zeros((m, K-1))
        self.t = np.zeros(K-1)
        
        # Convert y to one-hot encoding with simplex coding
        Y = self.simplex_encoding(y, K)
        
        # Optimization using Iterative Majorization
        self.optimize(X, Y)
    
    def simplex_encoding(self, y, K):
        U = np.eye(K) - (1 / K)
        return U[y]
    
    def optimize(self, X, Y):
        # Simplified version of the iterative majorization algorithm
        # This should include the steps to iteratively update W and t
        for iteration in range(100):
            # Compute q_ij, hinge loss, gradients, etc.
            # Update W and t
            pass

    def predict(self, X):
        # Prediction step
        pass


In [4]:
import numpy.linalg as la

class GenSVM:
    def __init__(self, lambda_param=1.0, p=2, kappa=0):
        self.lambda_param = lambda_param
        self.p = p
        self.kappa = kappa

    def fit(self, X, y):
        n, m = X.shape
        K = len(np.unique(y))
        self.W = np.zeros((m, K-1))
        self.t = np.zeros(K-1)
        
        # Convert y to one-hot encoding with simplex coding
        Y = self.simplex_encoding(y, K)
        
        # Optimization using Iterative Majorization
        self.optimize(X, Y)
    
    def simplex_encoding(self, y, K):
        U = np.eye(K) - (1 / K)
        Y = U[y]
        return Y[:, :-1]  # Return the first K-1 dimensions

    def optimize(self, X, Y):
        n, m = X.shape
        K = Y.shape[1] + 1
        for iteration in range(100):  # Number of iterations
            Q = X.dot(self.W) + self.t
            margins = np.maximum(0, 1 - (Y * Q).sum(axis=1, keepdims=True) + Q)
            margins[np.arange(n), Y.argmax(axis=1)] = 0  # No loss for the correct class
            
            loss = np.linalg.norm(margins, ord=self.p, axis=1).sum() + self.lambda_param * la.norm(self.W)
            grad_W = X.T.dot(margins) / n + self.lambda_param * self.W
            grad_t = margins.mean(axis=0)
            
            self.W -= 0.01 * grad_W  # Learning rate
            self.t -= 0.01 * grad_t
    
    def predict(self, X):
        Q = X.dot(self.W) + self.t
        return Q.argmax(axis=1)

# Instantiate and train the model
model = GenSVM()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Evaluate the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')


Accuracy: 53.33%


In [5]:
from sklearn.metrics import classification_report, confusion_matrix

# Print classification report
print(classification_report(y_test, y_pred))

# Print confusion matrix
print(confusion_matrix(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.62      1.00      0.77        10
           1       0.43      0.67      0.52         9
           2       0.00      0.00      0.00        11

    accuracy                           0.53        30
   macro avg       0.35      0.56      0.43        30
weighted avg       0.34      0.53      0.41        30

[[10  0  0]
 [ 3  6  0]
 [ 3  8  0]]


/home/amir/miniconda3/envs/PY/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/amir/miniconda3/envs/PY/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/amir/miniconda3/envs/PY/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(r